package com.example.EVS.Model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class VoterRequest {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long requestId;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String district;

    @Column(nullable = false)
    private String constituency;

    private String voterId; // Generated by Electoral Officer

    @Column(nullable = false)
    private String applicationStatus; // e.g., PENDING, APPROVED, REJECTED

    @Column(nullable = false)
    private Long userId; // Reference to Voter (User entity)
}
